package samples

/** 
 * Generated by: Default feature generator 
 */ 
class SimpleFeature extends org.boomslang.features.BoomslangFeature {

	def "Hit all elements on the screen"() {
	
		given:
			to (SimpleScreen);
		
		when:
		name.value $name
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		submit.click()
		
		where:
		$name | // TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder"
		"asdasd" | // TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter"
	}
	

}
