package org.boomslang.test.features


/** 
 * Generated by: STMPBot Feature Generator 
 */ 
class LoginFeature extends com.ubs.a00.boomslang.common.specification.CockpitFeatureSpecification {
    def "Login to Application"() {
    
        given:
          
          def loginScreen = new org.boomslang.test.screens.LoginScreen(bot)
        
        when:
            loginScreen.getPasswordTextfield().typeText("Pwd123")
    
    }
}
