package org.boomslang.test.features

/** 
 * Generated by: Default feature generator 
 */ 
class LoginFeature extends org.boomslang.features.BoomslangFeature {

	def "Login to Application"() {
	
		given:
			to (org.boomslang.test.screens.LoginScreen);
		
		when:
		password.value $password
		
		where:
		$password|_
		"Pwd123"|_
	}
	

}
