package com.ubs.a6t.test.features.simple

/** 
 * Generated by: Default feature generator 
 */ 
class MultiWidgetGroupsFeature extends org.boomslang.features.BoomslangFeature {

	def "Test Use Of Multiple"() {
	
		given:
			to (MultiWidgetGroupsScreen);
		
		when:
		login.value $login
		and:
		password.value $password
		and:
		passwordForgotten.click()
		and:
		register.click()
		
		where:
		$login | $password
		"Login Credentials" | "MySecretPassword"
	}
	

}
