package com.ubs.a6t.test.features.simple

/** 
 * Generated by: Default feature generator 
 */ 
class MultiComponentWithOwnWidgetsFeature extends org.boomslang.features.BoomslangFeature {

	def "Test Use Of Multiple"() {
	
		given:
			to (MultiComponentWithOwnWidgetsScreen);
		
		when:
		eMail.value $eMail
		and:
		name.value $name
		and:
		phoneNumber.value $phoneNumber
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		validate.click()
		and:
		submit.click()
		and:
		userName.value $userName
		and:
		password.value $password
		
		where:
		$eMail | $name | $password | $phoneNumber | // TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder" | 
		$userName
		"john.doe@test.com" | "John Doe" | "****" | "+ 41 225587" | // TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter" | 
		"Username"
	}
	

}
