package com.ubs.a6t.test.features.simple

/** 
 * Generated by: Default feature generator 
 */ 
class MultiComponentFeature extends org.boomslang.features.BoomslangFeature {

	def "Test Use Of Multiple"() {
	
		given:
			to (MultiComponentScreen);
		
		when:
		eMail.value $eMail
		and:
		name.value $name
		and:
		phoneNumber.value $phoneNumber
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		validate.click()
		and:
		submit.click()
		
		where:
		$eMail | $name | $phoneNumber | // TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder"
		"john.doe@test.com" | "John Doe" | "+ 41 225587" | // TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter"
	}
	

}
