package com.ubs.a6t.test.features.simple

/** 
 * Generated by: Default feature generator 
 */ 
class ScreenSwitchFeature extends org.boomslang.features.BoomslangFeature {

	def "Hit all elements on the screen"() {
	
		given:
			to (WidgetGroupInWidgetGroupScreen);
		
		when:
		yes.click()
		
		then:
		at MultiComponentScreen
		
		when:
		eMail.value $eMail
		
		then:
		at SimpleScreen
		
		when:
		name.value $name
		
		then:
		at WidgetGroupInWidgetGroupScreen
		
		when:
		clear.click()
		
		where:
		$eMail | $name
		"DSFDSF" | "BAFD"
	}
	

}
