package com.ubs.a6t.test.features.simple

/** 
 * Generated by: Default feature generator 
 */ 
class SimpleComponentFeature extends org.boomslang.features.BoomslangFeature {

	def "Reference Elements inside a component"() {
	
		given:
			to (SimpleComponentScreen);
		
		when:
		name.value $name
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		and:
		submit.click()
		
		where:
		$name | // TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder"
		"BlaBlub" | // TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter" | 
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter"
	}
	

}
