package com.ubs.a6t.test.features.simple

/** 
 * Generated by: Default feature generator 
 */ 
class TableFeature extends org.boomslang.features.BoomslangFeature {

	def "Click Table Handling"() {
	
		given:
			to (SimpleScreen);
		
		when:
		adress.click()
		
	}
	
	def "Select Table Handling"() {
	
		given:
			to (SimpleScreen);
		
		when:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		
		where:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder"
		|_
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter"
		|_
	}
	
	def "Type Table Handling"() {
	
		given:
			to (SimpleScreen);
		
		when:
		adress.value $adress
		
		where:
		$adress|_
		"Foo"|_
	}
	
	def "DoubleClick Table Handling"() {
	
		given:
			to (SimpleScreen);
		
		when:
		// TODO
		println "command actions of type BDoubleClickAction not yet implemented in compileAction"
		
	}
	
	def "Check Table Handling"() {
	
		given:
			to (SimpleScreen);
		
		when:
		// TODO
		println "command actions of type BCheckAction not yet implemented in compileAction"
		
	}
	

}
