package com.ubs.a6t.test.features.simple

/** 
 * Generated by: Default feature generator 
 */ 
class WidgetGroupInWidgetGroupFeature extends org.boomslang.features.BoomslangFeature {

	def "Hit all elements on the screen"() {
	
		given:
			to (WidgetGroupInWidgetGroupScreen);
		
		when:
		yes.click()
		and:
		no.click()
		and:
		clear.click()
		and:
		password.value $password
		and:
		submit.click()
		and:
		userName.value $userName
		and:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileAction"
		
		where:
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionPlaceholder" | 
		$password | $userName
		// TODO
		println "command actions of type BSelectAction not yet implemented in compileActionParameter" | 
		"******" | "UserName"
	}
	

}
